spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PICPAYTESTE_DB
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration/prod